'use strict';

const { models, sequelize } = require('../../models');
const { ROLES, PERMISSIONS } = require('../../config/constants');
const logger = require('../../config/logger');

const ROLE_DEFINITIONS = [
  { key: ROLES.ADMIN, name: 'Administrator', description: 'Full access across every module' },
  { key: ROLES.HR_MANAGER, name: 'HR Manager', description: 'Chief HR, reads all modules, suggests changes to owners' },
  { key: ROLES.HR, name: 'HR', description: 'Department scoped HR operations' },
  { key: ROLES.PAYROLL_MANAGER, name: 'Payroll Manager', description: 'CRUD over payroll data and structures' },
  { key: ROLES.PAYROLL_USER, name: 'Payroll User', description: 'Reads payroll data and releases funds' },
  { key: ROLES.IT_ADMIN, name: 'IT Administrator', description: 'Owns IT administration and device fleet' },
  {
    key: ROLES.TALENT_ACQUISITION_LEAD,
    name: 'Talent Acquisition Lead',
    description: 'Owns the hiring module across the organization',
  },
  { key: ROLES.EMPLOYEE, name: 'Employee', description: 'Employee self service surface' },
];

const ROLE_PERMISSIONS = {
  [ROLES.HR_MANAGER]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_STRUCTURE_READ,
    PERMISSIONS.PAYROLL_RULE_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.PAYRUN_READ,
    PERMISSIONS.PAYSLIP_READ,
    PERMISSIONS.SALARY_CHANGE_SUGGEST,
    PERMISSIONS.WORKING_SCHEDULE_READ,
    PERMISSIONS.WORKING_SCHEDULE_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.TIME_OFF_TYPE_READ,
    PERMISSIONS.TIME_OFF_TYPE_WRITE,
    PERMISSIONS.TIME_OFF_ALLOCATION_READ,
    PERMISSIONS.TIME_OFF_ALLOCATION_WRITE,
    PERMISSIONS.TIME_OFF_ALLOCATION_APPROVE,
    PERMISSIONS.TIME_OFF_REQUEST_READ,
    PERMISSIONS.TIME_OFF_REQUEST_APPROVE,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.HR_REQUEST_READ,
    PERMISSIONS.HR_REQUEST_WRITE,
    PERMISSIONS.HR_CHAT_READ,
    PERMISSIONS.HR_CHAT_WRITE,
    PERMISSIONS.IT_DEVICE_READ,
    PERMISSIONS.IT_SOFTWARE_READ,
    PERMISSIONS.IT_BASELINE_READ,
    PERMISSIONS.IT_EDR_READ,
    PERMISSIONS.IT_ONBOARDING_READ,
    PERMISSIONS.BENEFIT_PROVIDER_READ,
    PERMISSIONS.BENEFIT_PROVIDER_WRITE,
    PERMISSIONS.BENEFIT_PLAN_READ,
    PERMISSIONS.BENEFIT_PLAN_WRITE,
    PERMISSIONS.BENEFIT_ENROLLMENT_READ,
    PERMISSIONS.BENEFIT_ENROLLMENT_WRITE,
    PERMISSIONS.BENEFIT_ENROLLMENT_APPROVE,
    PERMISSIONS.BENEFIT_CLAIM_READ,
    PERMISSIONS.BENEFIT_CLAIM_WRITE,
    PERMISSIONS.BENEFIT_CLAIM_APPROVE,
    PERMISSIONS.LOAN_PROGRAM_READ,
    PERMISSIONS.LOAN_PROGRAM_WRITE,
    PERMISSIONS.LOAN_REQUEST_READ,
    PERMISSIONS.LOAN_APPROVE,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.DISCOUNT_PARTNER_READ,
    PERMISSIONS.DISCOUNT_PARTNER_WRITE,
    PERMISSIONS.REQUISITION_READ,
    PERMISSIONS.REQUISITION_WRITE,
    PERMISSIONS.JOB_POSTING_READ,
    PERMISSIONS.CANDIDATE_READ,
    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.INTERVIEW_READ,
    PERMISSIONS.OFFER_READ,
    PERMISSIONS.REFERRAL_READ,
    PERMISSIONS.REFERRAL_WRITE,
    PERMISSIONS.LOCATION_STANDARD_READ,
    PERMISSIONS.LOCATION_STANDARD_WRITE,
    PERMISSIONS.MOBILITY_PARTNER_READ,
    PERMISSIONS.MOBILITY_PARTNER_WRITE,
    PERMISSIONS.VISA_READ,
    PERMISSIONS.VISA_WRITE,
    PERMISSIONS.VISA_APPROVE,
    PERMISSIONS.RELOCATION_READ,
    PERMISSIONS.RELOCATION_WRITE,
    PERMISSIONS.RELOCATION_APPROVE,
    PERMISSIONS.IMMIGRATION_READ,
    PERMISSIONS.IMMIGRATION_WRITE,
    PERMISSIONS.TRAVEL_READ,
    PERMISSIONS.TRAVEL_WRITE,
    PERMISSIONS.TRAVEL_APPROVE,
  ],
  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.SALARY_CHANGE_SUGGEST,
    PERMISSIONS.WORKING_SCHEDULE_READ,
    PERMISSIONS.WORKING_SCHEDULE_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.TIME_OFF_TYPE_READ,
    PERMISSIONS.TIME_OFF_TYPE_WRITE,
    PERMISSIONS.TIME_OFF_ALLOCATION_READ,
    PERMISSIONS.TIME_OFF_ALLOCATION_WRITE,
    PERMISSIONS.TIME_OFF_ALLOCATION_APPROVE,
    PERMISSIONS.TIME_OFF_REQUEST_READ,
    PERMISSIONS.TIME_OFF_REQUEST_APPROVE,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.HR_REQUEST_READ,
    PERMISSIONS.HR_REQUEST_WRITE,
    PERMISSIONS.HR_CHAT_READ,
    PERMISSIONS.HR_CHAT_WRITE,
    PERMISSIONS.BENEFIT_PROVIDER_READ,
    PERMISSIONS.BENEFIT_PLAN_READ,
    PERMISSIONS.BENEFIT_ENROLLMENT_READ,
    PERMISSIONS.BENEFIT_ENROLLMENT_WRITE,
    PERMISSIONS.BENEFIT_CLAIM_READ,
    PERMISSIONS.BENEFIT_CLAIM_WRITE,
    PERMISSIONS.LOAN_PROGRAM_READ,
    PERMISSIONS.LOAN_REQUEST_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.DISCOUNT_PARTNER_READ,
  ],
  [ROLES.PAYROLL_MANAGER]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_WRITE,
    PERMISSIONS.PAYROLL_STRUCTURE_READ,
    PERMISSIONS.PAYROLL_STRUCTURE_WRITE,
    PERMISSIONS.PAYROLL_RULE_READ,
    PERMISSIONS.PAYROLL_RULE_WRITE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_WRITE,
    PERMISSIONS.PAYRUN_READ,
    PERMISSIONS.PAYRUN_WRITE,
    PERMISSIONS.PAYRUN_VALIDATE,
    PERMISSIONS.PAYSLIP_READ,
    PERMISSIONS.PAYSLIP_WRITE,
    PERMISSIONS.SALARY_CHANGE_DECIDE,
    PERMISSIONS.ADVANCE_SALARY_APPROVE,
    PERMISSIONS.BONUS_MANAGE,
    PERMISSIONS.LOAN_REQUEST_READ,
    PERMISSIONS.LOAN_APPROVE,
    PERMISSIONS.LOAN_DISBURSE,
  ],
  [ROLES.PAYROLL_USER]: [
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_STRUCTURE_READ,
    PERMISSIONS.PAYROLL_RULE_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.PAYRUN_READ,
    PERMISSIONS.PAYRUN_WRITE,
    PERMISSIONS.PAYSLIP_READ,
    PERMISSIONS.PAYSLIP_WRITE,
    PERMISSIONS.PAYMENT_RELEASE,
  ],
  [ROLES.IT_ADMIN]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.IT_DEVICE_READ,
    PERMISSIONS.IT_DEVICE_WRITE,
    PERMISSIONS.IT_DEVICE_ASSIGN,
    PERMISSIONS.IT_SOFTWARE_READ,
    PERMISSIONS.IT_SOFTWARE_WRITE,
    PERMISSIONS.IT_BASELINE_READ,
    PERMISSIONS.IT_BASELINE_WRITE,
    PERMISSIONS.IT_EDR_READ,
    PERMISSIONS.IT_EDR_WRITE,
    PERMISSIONS.IT_ONBOARDING_READ,
    PERMISSIONS.IT_ONBOARDING_WRITE,
    PERMISSIONS.IT_LEASE_READ,
    PERMISSIONS.IT_LEASE_WRITE,
  ],
  [ROLES.TALENT_ACQUISITION_LEAD]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.REQUISITION_READ,
    PERMISSIONS.REQUISITION_WRITE,
    PERMISSIONS.REQUISITION_APPROVE,
    PERMISSIONS.JOB_POSTING_READ,
    PERMISSIONS.JOB_POSTING_WRITE,
    PERMISSIONS.JOB_POSTING_PUBLISH,
    PERMISSIONS.JOB_BOARD_READ,
    PERMISSIONS.JOB_BOARD_WRITE,
    PERMISSIONS.CANDIDATE_READ,
    PERMISSIONS.CANDIDATE_WRITE,
    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_WRITE,
    PERMISSIONS.APPLICATION_PROGRESS,
    PERMISSIONS.INTERVIEW_READ,
    PERMISSIONS.INTERVIEW_WRITE,
    PERMISSIONS.INTERVIEW_FEEDBACK_WRITE,
    PERMISSIONS.OFFER_READ,
    PERMISSIONS.OFFER_WRITE,
    PERMISSIONS.OFFER_APPROVE,
    PERMISSIONS.REFERRAL_READ,
    PERMISSIONS.REFERRAL_WRITE,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.ADVANCE_SALARY_REQUEST,
    PERMISSIONS.ATTENDANCE_SELF_WRITE,
    PERMISSIONS.TIME_OFF_TYPE_READ,
    PERMISSIONS.TIME_OFF_REQUEST_READ,
    PERMISSIONS.TIME_OFF_REQUEST_WRITE,
    PERMISSIONS.FEEDBACK_WRITE,
    PERMISSIONS.HR_REQUEST_READ,
    PERMISSIONS.HR_REQUEST_WRITE,
    PERMISSIONS.HR_CHAT_WRITE,
    PERMISSIONS.BENEFIT_PLAN_READ,
    PERMISSIONS.BENEFIT_ENROLLMENT_READ,
    PERMISSIONS.BENEFIT_ENROLLMENT_WRITE,
    PERMISSIONS.BENEFIT_CLAIM_READ,
    PERMISSIONS.BENEFIT_CLAIM_WRITE,
    PERMISSIONS.LOAN_PROGRAM_READ,
    PERMISSIONS.LOAN_REQUEST_READ,
    PERMISSIONS.LOAN_REQUEST_WRITE,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.DISCOUNT_PARTNER_READ,
    PERMISSIONS.REFERRAL_SUBMIT,
    PERMISSIONS.REFERRAL_READ,
    PERMISSIONS.JOB_POSTING_READ,
    PERMISSIONS.LOCATION_STANDARD_READ,
    PERMISSIONS.VISA_READ,
    PERMISSIONS.RELOCATION_READ,
    PERMISSIONS.IMMIGRATION_READ,
    PERMISSIONS.TRAVEL_READ,
    PERMISSIONS.TRAVEL_WRITE,
  ],
};

async function seed() {
  await sequelize.transaction(async (transaction) => {
    for (const role of ROLE_DEFINITIONS) {
      await models.Role.findOrCreate({
        where: { key: role.key },
        defaults: { ...role, is_system: true },
        transaction,
      });
    }

    for (const key of Object.values(PERMISSIONS)) {
      await models.Permission.findOrCreate({
        where: { key },
        defaults: { key, description: key },
        transaction,
      });
    }

    const allRoles = await models.Role.findAll({ transaction });
    const allPermissions = await models.Permission.findAll({ transaction });
    const permByKey = Object.fromEntries(allPermissions.map((p) => [p.key, p]));

    for (const role of allRoles) {
      const wantedKeys = ROLE_PERMISSIONS[role.key] || [];
      const wantedPerms = wantedKeys.map((k) => permByKey[k]).filter(Boolean);
      await role.setPermissions(wantedPerms, { transaction });
    }
  });

  logger.info('Roles and permissions seeded');
}

module.exports = { seed };

if (require.main === module) {
  seed()
    .then(() => process.exit(0))
    .catch((err) => {
      logger.error(err);
      process.exit(1);
    });
}
